
run interior-point/order-of-magnitude-floor/on/on/main.m
run interior-point/order-of-magnitude-floor/on/off/main.m
run interior-point/order-of-magnitude-floor/off/on/main.m
run interior-point/order-of-magnitude-floor/off/off/main.m
run interior-point/order-of-magnitude-round/on/on/main.m
run interior-point/order-of-magnitude-round/on/off/main.m
run interior-point/order-of-magnitude-round/off/on/main.m
run interior-point/order-of-magnitude-round/off/off/main.m
run interior-point/almost-exact-solution/on/on/main.m
run interior-point/almost-exact-solution/on/off/main.m
run interior-point/almost-exact-solution/off/on/main.m
run interior-point/almost-exact-solution/off/off/main.m
run interior-point/ones/on/on/main.m
run interior-point/ones/on/off/main.m
run interior-point/ones/off/on/main.m
run interior-point/ones/off/off/main.m
run SQP/order-of-magnitude-floor/on/on/main.m
run SQP/order-of-magnitude-floor/on/off/main.m
run SQP/order-of-magnitude-floor/off/on/main.m
run SQP/order-of-magnitude-floor/off/off/main.m
run SQP/order-of-magnitude-round/on/on/main.m
run SQP/order-of-magnitude-round/on/off/main.m
run SQP/order-of-magnitude-round/off/on/main.m
run SQP/order-of-magnitude-round/off/off/main.m
run SQP/almost-exact-solution/on/on/main.m
run SQP/almost-exact-solution/on/off/main.m
run SQP/almost-exact-solution/off/on/main.m
run SQP/almost-exact-solution/off/off/main.m
run SQP/ones/on/on/main.m
run SQP/ones/on/off/main.m
run SQP/ones/off/on/main.m
run SQP/ones/off/off/main.m
