
run interior-point/order-of-magnitude-floor/on/on/iter_1/main.m
run interior-point/order-of-magnitude-floor/on/on/iter_2/main.m
run interior-point/order-of-magnitude-floor/on/on/iter_3/main.m
run interior-point/order-of-magnitude-floor/on/on/iter_4/main.m
run interior-point/order-of-magnitude-floor/on/off/iter_1/main.m
run interior-point/order-of-magnitude-floor/on/off/iter_2/main.m
run interior-point/order-of-magnitude-floor/on/off/iter_3/main.m
run interior-point/order-of-magnitude-floor/on/off/iter_4/main.m
run interior-point/order-of-magnitude-floor/off/on/iter_1/main.m
run interior-point/order-of-magnitude-floor/off/on/iter_2/main.m
run interior-point/order-of-magnitude-floor/off/on/iter_3/main.m
run interior-point/order-of-magnitude-floor/off/on/iter_4/main.m
run interior-point/order-of-magnitude-floor/off/off/iter_1/main.m
run interior-point/order-of-magnitude-floor/off/off/iter_2/main.m
run interior-point/order-of-magnitude-floor/off/off/iter_3/main.m
run interior-point/order-of-magnitude-floor/off/off/iter_4/main.m
run interior-point/order-of-magnitude-round/on/on/iter_1/main.m
run interior-point/order-of-magnitude-round/on/on/iter_2/main.m
run interior-point/order-of-magnitude-round/on/on/iter_3/main.m
run interior-point/order-of-magnitude-round/on/off/iter_1/main.m
run interior-point/order-of-magnitude-round/on/off/iter_2/main.m
run interior-point/order-of-magnitude-round/on/off/iter_3/main.m
run interior-point/order-of-magnitude-round/off/on/iter_1/main.m
run interior-point/order-of-magnitude-round/off/on/iter_2/main.m
run interior-point/order-of-magnitude-round/off/on/iter_3/main.m
run interior-point/order-of-magnitude-round/off/off/iter_1/main.m
run interior-point/order-of-magnitude-round/off/off/iter_2/main.m
run interior-point/order-of-magnitude-round/off/off/iter_3/main.m
run interior-point/almost-exact-solution/on/on/iter_1/main.m
run interior-point/almost-exact-solution/on/on/iter_2/main.m
run interior-point/almost-exact-solution/on/on/iter_3/main.m
run interior-point/almost-exact-solution/on/off/iter_1/main.m
run interior-point/almost-exact-solution/on/off/iter_2/main.m
run interior-point/almost-exact-solution/on/off/iter_3/main.m
run interior-point/almost-exact-solution/off/on/iter_1/main.m
run interior-point/almost-exact-solution/off/on/iter_2/main.m
run interior-point/almost-exact-solution/off/on/iter_3/main.m
run interior-point/almost-exact-solution/off/off/iter_1/main.m
run interior-point/almost-exact-solution/off/off/iter_2/main.m
run interior-point/almost-exact-solution/off/off/iter_3/main.m
run interior-point/ones/on/on/iter_1/main.m
run interior-point/ones/on/on/iter_2/main.m
run interior-point/ones/on/on/iter_3/main.m
run interior-point/ones/on/on/iter_4/main.m
run interior-point/ones/on/off/iter_1/main.m
run interior-point/ones/on/off/iter_2/main.m
run interior-point/ones/on/off/iter_3/main.m
run interior-point/ones/on/off/iter_4/main.m
run interior-point/ones/off/on/iter_1/main.m
run interior-point/ones/off/on/iter_2/main.m
run interior-point/ones/off/on/iter_3/main.m
run interior-point/ones/off/on/iter_4/main.m
run interior-point/ones/off/off/iter_1/main.m
run interior-point/ones/off/off/iter_2/main.m
run interior-point/ones/off/off/iter_3/main.m
run interior-point/ones/off/off/iter_4/main.m
run SQP/order-of-magnitude-floor/on/on/iter_1/main.m
run SQP/order-of-magnitude-floor/on/on/iter_2/main.m
run SQP/order-of-magnitude-floor/on/on/iter_3/main.m
run SQP/order-of-magnitude-floor/on/on/iter_4/main.m
run SQP/order-of-magnitude-floor/on/off/iter_1/main.m
run SQP/order-of-magnitude-floor/on/off/iter_2/main.m
run SQP/order-of-magnitude-floor/on/off/iter_3/main.m
run SQP/order-of-magnitude-floor/on/off/iter_4/main.m
run SQP/order-of-magnitude-floor/off/on/iter_1/main.m
run SQP/order-of-magnitude-floor/off/on/iter_2/main.m
run SQP/order-of-magnitude-floor/off/on/iter_3/main.m
run SQP/order-of-magnitude-floor/off/on/iter_4/main.m
run SQP/order-of-magnitude-floor/off/off/iter_1/main.m
run SQP/order-of-magnitude-floor/off/off/iter_2/main.m
run SQP/order-of-magnitude-floor/off/off/iter_3/main.m
run SQP/order-of-magnitude-floor/off/off/iter_4/main.m
run SQP/order-of-magnitude-round/on/on/iter_1/main.m
run SQP/order-of-magnitude-round/on/on/iter_2/main.m
run SQP/order-of-magnitude-round/on/on/iter_3/main.m
run SQP/order-of-magnitude-round/on/off/iter_1/main.m
run SQP/order-of-magnitude-round/on/off/iter_2/main.m
run SQP/order-of-magnitude-round/on/off/iter_3/main.m
run SQP/order-of-magnitude-round/off/on/iter_1/main.m
run SQP/order-of-magnitude-round/off/on/iter_2/main.m
run SQP/order-of-magnitude-round/off/on/iter_3/main.m
run SQP/order-of-magnitude-round/off/off/iter_1/main.m
run SQP/order-of-magnitude-round/off/off/iter_2/main.m
run SQP/order-of-magnitude-round/off/off/iter_3/main.m
run SQP/almost-exact-solution/on/on/iter_1/main.m
run SQP/almost-exact-solution/on/on/iter_2/main.m
run SQP/almost-exact-solution/on/on/iter_3/main.m
run SQP/almost-exact-solution/on/off/iter_1/main.m
run SQP/almost-exact-solution/on/off/iter_2/main.m
run SQP/almost-exact-solution/on/off/iter_3/main.m
run SQP/almost-exact-solution/off/on/iter_1/main.m
run SQP/almost-exact-solution/off/on/iter_2/main.m
run SQP/almost-exact-solution/off/on/iter_3/main.m
run SQP/almost-exact-solution/off/off/iter_1/main.m
run SQP/almost-exact-solution/off/off/iter_2/main.m
run SQP/almost-exact-solution/off/off/iter_3/main.m
run SQP/ones/on/on/iter_1/main.m
run SQP/ones/on/on/iter_2/main.m
run SQP/ones/on/on/iter_3/main.m
run SQP/ones/on/on/iter_4/main.m
run SQP/ones/on/off/iter_1/main.m
run SQP/ones/on/off/iter_2/main.m
run SQP/ones/on/off/iter_3/main.m
run SQP/ones/on/off/iter_4/main.m
run SQP/ones/off/on/iter_1/main.m
run SQP/ones/off/on/iter_2/main.m
run SQP/ones/off/on/iter_3/main.m
run SQP/ones/off/on/iter_4/main.m
run SQP/ones/off/off/iter_1/main.m
run SQP/ones/off/off/iter_2/main.m
run SQP/ones/off/off/iter_3/main.m
run SQP/ones/off/off/iter_4/main.m
