
run interior-point/order-of-magnitude-floor/off/off/iter_1/main.m
run interior-point/order-of-magnitude-floor/off/off/iter_2/main.m
run interior-point/order-of-magnitude-floor/off/off/iter_3/main.m
run interior-point/order-of-magnitude-floor/off/off/iter_4/main.m
run interior-point/order-of-magnitude-round/off/off/iter_1/main.m
run interior-point/order-of-magnitude-round/off/off/iter_2/main.m
run interior-point/order-of-magnitude-round/off/off/iter_3/main.m
run interior-point/order-of-magnitude-round/off/off/iter_4/main.m
run interior-point/almost-exact-solution/off/off/iter_1/main.m
run interior-point/almost-exact-solution/off/off/iter_2/main.m
run interior-point/almost-exact-solution/off/off/iter_3/main.m
run interior-point/almost-exact-solution/off/off/iter_4/main.m
run interior-point/ones/off/off/iter_1/main.m
run interior-point/ones/off/off/iter_2/main.m
run interior-point/ones/off/off/iter_3/main.m
run interior-point/ones/off/off/iter_4/main.m
run SQP/order-of-magnitude-floor/off/off/iter_1/main.m
run SQP/order-of-magnitude-floor/off/off/iter_2/main.m
run SQP/order-of-magnitude-floor/off/off/iter_3/main.m
run SQP/order-of-magnitude-floor/off/off/iter_4/main.m
run SQP/order-of-magnitude-round/off/off/iter_1/main.m
run SQP/order-of-magnitude-round/off/off/iter_2/main.m
run SQP/order-of-magnitude-round/off/off/iter_3/main.m
run SQP/order-of-magnitude-round/off/off/iter_4/main.m
run SQP/almost-exact-solution/off/off/iter_1/main.m
run SQP/almost-exact-solution/off/off/iter_2/main.m
run SQP/almost-exact-solution/off/off/iter_3/main.m
run SQP/almost-exact-solution/off/off/iter_4/main.m
run SQP/ones/off/off/iter_1/main.m
run SQP/ones/off/off/iter_2/main.m
run SQP/ones/off/off/iter_3/main.m
run SQP/ones/off/off/iter_4/main.m
